/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class TestApp {

    @Test
    void placeholderTest() {
        // This is a blank test placeholder for App.java
        // You can add real tests for App's behavior later
    }
}
