/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class TestCutie {

    @Test
    void testPuppy() {
        Cutie puppy = new Puppy();
        assertEquals("It is a baby dog.", puppy.description());
        assertEquals(8, puppy.cutenessRating());
    }

    @Test
    void testKitty() {
        Cutie kitty = new Kitty();
        assertEquals("It is a baby cat.", kitty.description());
        assertEquals(9, kitty.cutenessRating());
    }

    @Test
    void testPygmyMarmoset() {
        Cutie marmoset = new PygmyMarmoset();
        assertEquals("It is a very small Monkey.", marmoset.description());
        assertEquals(10, marmoset.cutenessRating());
    }
}
