/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Test;

class TestQueueTees {

    @Test
    void testEnqueueDequeue() {
        QueueTees queue = new QueueTees(3);
        Cutie puppy = new Puppy();
        Cutie kitty = new Kitty();

        assertEquals(0, queue.size());
        queue.enqueue(puppy);
        queue.enqueue(kitty);
        assertEquals(2, queue.size());

        Cutie first = queue.dequeue();
        assertEquals(puppy, first);
        Cutie second = queue.dequeue();
        assertEquals(kitty, second);
        assertEquals(0, queue.size());
    }

    @Test
    void testQueueFullException() {
        QueueTees queue = new QueueTees(1);
        queue.enqueue(new Puppy());

        IllegalStateException exception = assertThrows(IllegalStateException.class, () -> {
            queue.enqueue(new Kitty());
        });
        assertEquals("Queue is full! Cannot enqueue.", exception.getMessage());
    }

    @Test
    void testQueueEmptyException() {
        QueueTees queue = new QueueTees(1);
        IllegalStateException exception = assertThrows(IllegalStateException.class, () -> {
            queue.dequeue();
        });
        assertEquals("Queue is empty! Cannot dequeue.", exception.getMessage());
    }
}
